// Usernames que no se pueden reclamar porque colisionan con rutas
// reales o son nombres sensibles de la plataforma.
export const RESERVED_USERNAMES: ReadonlySet<string> = new Set([
  "login",
  "menu",
  "register",
  "forgot-password",
  "reset-password",
  "dashboard",
  "control",
  "api",
  "invitaciones",
  "_next",
  "favicon.ico",
  "robots.txt",
  "sitemap.xml",
  "admin",
  "static",
  "assets",
  "public",
  "u",
  "miselink",
  "mise",
  "soporte",
  "support",
  "terms",
  "privacy",
  "legal",
  "settings",
  "account",
  "cuenta",
]);
